{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5d340b96-8960-4e49-aad0-341f6fb5312e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "\n",
    "# --- Logic ---\n",
    "expression = \"\"\n",
    "\n",
    "def press(val):\n",
    "    global expression\n",
    "    if val == \"=\":\n",
    "        try:\n",
    "            result = str(eval(expression))\n",
    "            display.config(text=result)\n",
    "            expression = result\n",
    "        except:\n",
    "            display.config(text=\"Error\")\n",
    "            expression = \"\"\n",
    "    elif val == \"C\":\n",
    "        expression = \"\"\n",
    "        display.config(text=\"0\")\n",
    "    elif val == \"⌫\":\n",
    "        expression = expression[:-1]\n",
    "        display.config(text=expression if expression else \"0\")\n",
    "    else:\n",
    "        expression += str(val)\n",
    "        display.config(text=expression)\n",
    "\n",
    "# --- Window ---\n",
    "root = tk.Tk()\n",
    "root.title(\"Calculator\")\n",
    "root.resizable(False, False)\n",
    "root.configure(bg=\"#f0f0f0\")\n",
    "\n",
    "# --- Display ---\n",
    "display = tk.Label(\n",
    "    root,\n",
    "    text=\"0\",\n",
    "    anchor=\"e\",\n",
    "    font=(\"Courier\", 28),\n",
    "    bg=\"white\",\n",
    "    fg=\"#222\",\n",
    "    relief=\"flat\",\n",
    "    bd=0,\n",
    "    padx=12,\n",
    "    pady=16,\n",
    "    width=14\n",
    ")\n",
    "display.grid(row=0, column=0, columnspan=4, padx=12, pady=(12, 4), sticky=\"ew\")\n",
    "\n",
    "# --- Button layout ---\n",
    "buttons = [\n",
    "    [\"C\", \"⌫\", \"%\", \"/\"],\n",
    "    [\"7\", \"8\", \"9\", \"*\"],\n",
    "    [\"4\", \"5\", \"6\", \"-\"],\n",
    "    [\"1\", \"2\", \"3\", \"+\"],\n",
    "    [\"0\", \".\", \"\", \"=\"],\n",
    "]\n",
    "\n",
    "for r, row in enumerate(buttons):\n",
    "    for c, label in enumerate(row):\n",
    "        if label == \"\":\n",
    "            continue  # skip empty cell\n",
    "\n",
    "        is_op = label in (\"+\", \"-\", \"*\", \"/\", \"%\", \"=\", \"C\", \"⌫\")\n",
    "        bg = \"#d6d6d6\" if is_op else \"white\"\n",
    "        fg = \"#c0392b\" if label == \"=\" else \"#333\"\n",
    "        if label in (\"C\", \"⌫\"):\n",
    "            fg = \"#555\"\n",
    "\n",
    "        span = 2 if label == \"0\" else 1\n",
    "\n",
    "        btn = tk.Button(\n",
    "            root,\n",
    "            text=label,\n",
    "            font=(\"Courier\", 18),\n",
    "            bg=bg,\n",
    "            fg=fg,\n",
    "            activebackground=\"#bbb\" if is_op else \"#e8e8e8\",\n",
    "            relief=\"flat\",\n",
    "            bd=0,\n",
    "            cursor=\"hand2\",\n",
    "            command=lambda v=label: press(v)\n",
    "        )\n",
    "        btn.grid(\n",
    "            row=r + 1,\n",
    "            column=c,\n",
    "            columnspan=span,\n",
    "            padx=5,\n",
    "            pady=5,\n",
    "            ipadx=10,\n",
    "            ipady=12,\n",
    "            sticky=\"nsew\"\n",
    "        )\n",
    "\n",
    "# Make grid responsive\n",
    "for i in range(5):\n",
    "    root.grid_columnconfigure(i, weight=1)\n",
    "\n",
    "root.mainloop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e330af77-c7bc-48d6-9a77-fa6e46a2a3f1",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
